version: '3.8'

services:

  tomcat-one:
    image: tomcat-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/conf/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
    environment:
      CATALINA_HOME: /opt/tomcat
      PATH: /opt/tomcat/bin:$PATH

  tomcat-two:
    image: tomcat-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./tomcat/conf/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
    environment:
      CATALINA_HOME: /opt/tomcat
      PATH: /opt/tomcat/bin:$PATH

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: